import Head from 'next/head'
import { useState } from "react";
import { BsFillMoonStarsFill } from 'react-icons/bs'
import Footer from '../components/Footer';
import FullScreenNavbar from '../components/FullScreenNavbar';

const About = () => {
    const [darkMode, setDarkMode] = useState(false);
    return (
      <div className={darkMode ? "dark" : ""}>
      <Head>
      <title>Dun Yan</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className="bg-white px-10 lg:px-40 dark:bg-gray-900 py-6">
            <section className="min-h-screen">
              <nav className="py-10 mb-12 flex justify-between dark:text-slate-200">
                  <FullScreenNavbar />
                  <ul className="flex items-center">
                  <li><BsFillMoonStarsFill className="cursor-pointer text-slate-600 dark:text-slate-200" onClick={() => setDarkMode(!darkMode)}/></li>
                  </ul>
              </nav>

              {/*Descriptions*/}
              <div className="text-left p-10">
                <h2 className="text-4xl py-2 text-teal-600 font-medium md:text-4xl">My Journey</h2>
                <p className="text-md py-5 leading-8 text-gray-800 md:text-l max-w-xl dark:text-slate-200">Essay</p>
              </div>

              <Footer />
          </section>
        </main>
      </div>
    );
}
 
export default About;