import Head from 'next/head'
import Image from 'next/image'
import { useState } from "react";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from 'react-icons/bs'
import deved from "../public/dev-ed-wave.png";
import Projects from '../components/Projects';
import Footer from '../components/Footer';
import FullScreenNavbar from '../components/FullScreenNavbar';
import profilePic from '../public/boy-drawing-on-tablet-3025702-2526900.png';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Dun Yan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 lg:px-40 dark:bg-gray-900 py-6">
        <section className="min-h-screen">
          {/*Navbar*/}
          <nav className="py-10 mb-12 flex justify-between dark:text-slate-200">
          <FullScreenNavbar />
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill className="cursor-pointer text-slate-600 dark:text-slate-200" onClick={() => setDarkMode(!darkMode)}/></li>
            </ul>
          </nav>

          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Dun Yan</h2>
            <h3 className="text-2xl py-2 md:text-3xl text-gray-800 dark:text-slate-200">Junior Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-l max-w-xl mx-auto dark:text-slate-200">Hey! It's Dun Yan and I'm a Web Developer based in Kuala Lumpur. Malaysia. Besides enjoying writing NextJS, Bootstrap, Tailwind. I also have a solid foundation in UI design with Figma.</p>
            <p className="text-md leading-8 text-gray-800 md:text-l max-w-xl mx-auto dark:text-slate-200">Contact me down below👇</p>
          </div>

          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-slate-200">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillGithub />
          </div>

          <div class="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
            <Image src={profilePic} layout="fill" objectFit="cover" />
          </div>
        </section>
        {/*Projects List*/}
        <Projects />

        {/*Footer*/}
        <Footer />
      </main>
    </div>
  )
}
